<?php
namespace app\admin\controller;

use think\Controller;
use think\Cookie;
use think\Session;
use think\Db;
class Base extends Controller{

    public $isLogin = 0;
    public $userInfo = [];
    public $url = [];

    public function _initialize(){

        parent::_initialize(); // TODO: Change the autogenerated stub

        // 取出session
        $session = Session::get(md5('admin_session'));

        if($session){

            // 查询数据库是否有这个用户
            $result = Db::table("xm_admin_user")->where(['session_token'=>$session])->find();
            if($result){

                $this->isLogin = 1;
                $this->userInfo = $result;
                $this->assign(['userinfo'=>$this->userInfo]);
            }
        }else{
            // 获取cookie
            $cookie = Cookie::get(md5("admin_cookie"));

            // 查询用户
            $result = Db::table("xm_admin_user")->where(['cookie_token'=>$cookie])->find();
            if($result){

                $this->isLogin = 1;
                $this->userInfo = $result;
                $this->assign(['userinfo'=>$this->userInfo]);
            }
        }

        // 判断当前控制器
        if (strtolower(request()->controller()) != 'login'){

            // 用户ID
            $userId = isset($this->userInfo['id']) ? $this->userInfo['id'] : 0;
            // 查询当前用户的权限ID
            $permissionID = Db::table('xm_user_role')
                ->alias('a')
                ->join('xm_role b','a.role_id = b.id')
                ->join('xm_role_permission c','b.id = c.role_id')
                ->where(['a.user_id'=>$userId])
                ->find();

            $permissionID = explode(',',$permissionID['permission_id']);

            // 查询权限URL
            $url = [];
            foreach ($permissionID as $key => $value){

                $row = Db::table('xm_permission')->where(['id'=>$value])->find();

                $url[] = $row['rute'];
            }

            $this->url = $url;
        }

    }

}